### ISSUE TITLE
#3 create foundation to the Text mining file

### ISSUE THREAD

**Issue by haraldsDev** [lisja/KIK-LG211_HALM#3]
needs to be created a file -> then proceed with the Beautiful Soup

**Comment by haraldsDev** [comment]
– just playing around with Issues.
@mikzolot , I try first creating the text mining file – and then you could add something on top of it.
Do you also receive an email notification of this, 'cause i mentioned you?

**Comment by mikzolot** [comment]
> @haraldsDev Hi! I can see the message, but didnt get any email notifications about it:/

**Comment by mikzolot** [comment]
made a little change to avoid the urllib.error.URLError

**Comment by haraldsDev** [comment]
@mikzolot – ah, good!
the initial code didn't throw an error for me though – perhaps because I was working on a local machine and outputting locally...

**Comment by lisja** [comment]
I think this is ok so I'll close this :)
