### ISSUE TITLE
#5 HTML To-do

### ISSUE THREAD

**Issue by shimley** [lisja/KIK-LG211_HALM#5]
These should be at least done for the HTML task:

- [x] Headings and paragraphs
- [x] Links
- [x] Text formatting: boldface, italics, underlined text
- [x] Images
- [x] Lists
- [x] Tables

Additionally we can do these:

- [x] Text styles
- [ ] Page layouts

**Comment by shimley** [comment]
I've already done a heading and paragraphs. I've also added an image. The image part can be expanded by changing its size. I may do that myself later but if someone else is up for it, go for it!

**Comment by lisja** [comment]
I added a link.

**Comment by mikzolot** [comment]
Lists, tables, text formatting

**Comment by shimley** [comment]
Changed font color, size and style.
